# A chave principal 'grafana:' que agrupa todas as configurações
grafana:
  # --- PLUGINS (mantido) ---
  plugins:
    - grafana-athena-datasource

  # --- Sidecar para datasources (mantido) ---
  sidecar:
    datasources:
      enabled: true

  # --- Service Account IRSA (mantido) ---
  serviceAccount:
    create: true
    name: "grafana"
    annotations:
      eks.amazonaws.com/role-arn: "arn:aws:iam::920120425244:role/ilia-desafio-grafana-irsa-role"

  # --- Recursos (mantido) ---
  resources:
    limits:
      cpu: "1"
      memory: "1Gi"
    requests:
      cpu: "300m"
      memory: "300Mi"

  # --- senha grafana --- #
  admin:
    existingSecret: grafana-admin
    userKey: admin-user
    passwordKey: admin-password
    
  # --- pvc grafana --- #
  persistence:
    enabled: true
    type: pvc
    accessModes: ["ReadWriteOnce"]
    size: 5Gi
    finalizers:
      - kubernetes.io/pvc-protection

  # --- Datasource do Athena (mantido) ---
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Athena
          type: grafana-athena-datasource
          access: proxy
          isDefault: true
          jsonData:
            authType: default
            defaultRegion: "us-east-1"
            catalog: "AwsDataCatalog"
            database: "ilia_desafio_db"
            workgroup: "ilia-desafio-workgroup"

  # --- Alta disponibilidade simples e rollout estável ---
  replicas: 2
  podDisruptionBudget:
    enabled: true
    minAvailable: 1

  # Troca 1×1; não cria 3º pod => sem Pending e sem downtime.
  deploymentStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
