# A chave principal 'grafana:' que agrupa todas as configurações
grafana:
  # --- Bloco da Service Account (IRSA) ---
  serviceAccount:
    create: true
    name: grafana
    annotations:
      eks.amazonaws.com/role-arn: "arn:aws:iam::920120425244:role/ilia-desafio-grafana-irsa-role"

  # --- Bloco de Recursos (CPU/Memória) ---
  resources:
    limits:
      cpu: "1"
      memory: "1Gi"
    requests:
      cpu: "200m"
      memory: "256Mi"

  # --- Bloco NOVO para provisionar o Datasource do Athena ---
  datasources:
    # O nome do arquivo de configuração que o Helm vai criar dentro do cluster
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Athena
          type: grafana-athena-datasource
          access: proxy
          isDefault: true # Define este como o datasource padrão
          jsonData:
            authType: default
            defaultRegion: "us-east-1"
            catalog: "AwsDataCatalog"
            database: "ilia_desafio_db"
            workgroup: "ilia-desafio-workgroup"