grafana:
  # Plugins
  plugins:
    - grafana-athena-datasource

  # Sidecars
  sidecar:
    datasources:
      enabled: true

  # IRSA
  serviceAccount:
    create: true
    name: "grafana"
    annotations:
      eks.amazonaws.com/role-arn: "arn:aws:iam::920120425244:role/ilia-desafio-grafana-irsa-role"

  # Recursos
  resources:
    limits:
      cpu: "1"
      memory: "1Gi"
    requests:
      cpu: "300m"
      memory: "300Mi"

  # Senha via Secret existente
  admin:
    existingSecret: grafana-admin
    userKey: admin-user
    passwordKey: admin-password

  # Persistência (EBS / RWO)
  persistence:
    enabled: true
    type: pvc
    accessModes: ["ReadWriteOnce"]
    storageClassName: gp3
    size: 5Gi
    finalizers:
      - kubernetes.io/pvc-protection

  # Réplicas (1 para EBS/RWO)
  replicas: 1

  # PDB desabilitado (1 réplica)
  podDisruptionBudget:
    enabled: false

  # Rollout 1x1 sem downtime
  deploymentStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1

  # Datasource do Athena + Prometheus + Loki
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Athena
          type: grafana-athena-datasource
          access: proxy
          isDefault: true
          jsonData:
            authType: default
            defaultRegion: "us-east-1"
            catalog: "AwsDataCatalog"
            database: "ilia_desafio_db"
            workgroup: "ilia-desafio-workgroup"

        - name: Prometheus
          type: prometheus
          access: proxy
          url: http://kube-prometheus-kube-prome-prometheus.monitoring.svc.cluster.local:9090
 
