grafana:
  serviceAccount:
    create: true
    name: grafana
    automountServiceAccountToken: true
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::920120425244:role/ilia-desafio-grafana-irsa-role

  resources:
    limits:
      cpu: "1"
      memory: "1Gi"
    requests:
      cpu: "200m"
      memory: "256Mi"

  env:
    AWS_REGION: us-east-1
