serviceAccount:
  create: true
  name: "grafana"
  # anotação que conecta a Service Account ao IAM Role
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::920120425244:role/ilia-desafio-grafana-irsa-role" # <<< SUBSTITUA PELO SEU ACCOUNT ID
resources:
  requests:
    cpu: "200m"      
    memory: "256Mi"  

  limits:
    cpu: "1"         
    memory: "1Gi"    
    #teste de sync