{{- if .Values.metrics.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "api.fullname" . }}
  namespace: monitoring
  labels:
    release: kube-prometheus
spec:
  namespaceSelector:
    matchNames:
      - api
  selector:
    matchLabels:
      app: {{ include "api.fullname" . }}
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
{{- end }}
