apiVersion: v1
kind: Service
metadata:
  name: {{ include "api.fullname" . }}
  labels:
    app: {{ include "api.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}       # 80
      targetPort: {{ .Values.service.targetPort }}  # 8000
      protocol: TCP
    - name: metrics                           #  Prometheus
      port: {{ .Values.service.targetPort }}  # 8000 (mesma porta do /metrics)
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
  selector:
    app: {{ include "api.fullname" . }}
