# helm-charts-ilia/apps/fluent-bit-application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fluent-bit
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://aws.github.io/eks-charts
    chart: aws-for-fluent-bit
    targetRevision: 0.1.33
    helm:
      releaseName: fluent-bit
      values: |
        # Bloco da Service Account para forçar o uso do IRSA
        serviceAccount:
          create: true
          name: "fluent-bit"
          annotations:
            # O ARN correto que você confirmou
            eks.amazonaws.com/role-arn: "arn:aws:iam::920120425244:role/ilia-desafio-fluent-bit-irsa-role"

        # Configuração para enviar os logs para o CloudWatch
        cloudWatch:
          enabled: true
          region: "us-east-1"
          logGroupName: "/aws/eks/ilia-desafio/logs"
          logRetentionDays: 7

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
