# helm-charts-ilia/apps/fluent-bit-application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fluent-bit
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://aws.github.io/eks-charts
    chart: aws-for-fluent-bit
    targetRevision: 0.1.33
    helm:
      releaseName: fluent-bit
      values: |
        # Removido o bloco serviceAccount para não usar IRSA.

        # Adiciona as chaves do Secret como variáveis de ambiente no pod.
        extraEnvVars:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: fluent-bit-aws-credentials
                key: AWS_ACCESS_KEY_ID
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: fluent-bit-aws-credentials
                key: AWS_SECRET_ACCESS_KEY

        cloudWatch:
          enabled: true
          region: "us-east-1"
          logGroupName: "/aws/eks/ilia-desafio/logs"
          logRetentionDays: 7

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
