apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/LuanCristopher/helm-charts-ilia.git
    targetRevision: main                
    path: grafana
    helm:
      releaseName: grafana
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring


  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true        


  ignoreDifferences:
    - group: apps
      kind: Deployment
      namespace: monitoring
      name: grafana
      jqPathExpressions:
        - .spec.template.metadata.annotations["checksum/config"]
        - .spec.template.metadata.annotations["checksum/dashboards-config"]
        - .spec.template.metadata.annotations["checksum/dashboards-json-config"]
        - .spec.template.metadata.annotations["checksum/secret"]
        - .spec.template.metadata.annotations["checksum/sc-dashboard-provider-config"]
        - .spec.template.metadata.annotations["checksum/datasources-json-config"]
