apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: monitoring-critical
value: 100000
preemptionPolicy: PreemptLowerPriority
globalDefault: false
description: "Prioriza pods de observabilidade (ex.: Grafana)."
