apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: api-python
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/LuanCristopher/helm-charts-ilia.git
    targetRevision: main
    path: api
    helm:
      releaseName: api-python
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: api
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
