image:
  repository: 920120425244.dkr.ecr.us-east-1.amazonaws.com/ilia-desafio-api
  tag: "64cd2b7a699e08460fedd067349d272a034becf3" # a pipeline vai trocar para o SHA
  pullPolicy: IfNotPresent
replicaCount: 1
service:
  type: ClusterIP
  port: 80
  targetPort: 8000
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 256Mi
env: []
podAnnotations: {}
