name: Helm CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  helm_ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      - name: Instalar o Helm
        uses: azure/setup-helm@v4
        with:
          version: '3.x'

      - name: Adionando Repositório do Grafana
        run: helm repo add grafana https://grafana.github.io/helm-charts

      - name: Atualizar Repositórios do Helm
        run: helm repo update

      - name: Lint (Validar a Sintaxe) do Chart do Grafana
        run: helm lint ./helm-charts/grafana

      - name: Dry Run (Simular Deploy) do Chart do Grafana
        run: helm upgrade --install grafana grafana/grafana --namespace monitoring --dry-run --debug