name: Helm CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  helm_ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      - name: Instalar o Helm
        uses: azure/setup-helm@v4
        with:
          version: 'v3.15.2'

      - name: Adicionar Repositório do Grafana
        run: helm repo add grafana https://grafana.github.io/helm-charts

      - name: Atualizar Repositórios do Helm
        run: helm repo update
      
      # CORREÇÃO: O caminho correto é apenas 'grafana/'
      - name: Lint (Validar a Sintaxe) do Chart
        run: helm lint grafana/

      # CORREÇÃO: O caminho correto para o values.yaml é 'grafana/values.yaml'
      - name: Template (Validar a Lógica) do Chart
        run: helm template grafana grafana/grafana -f grafana/values.yaml --namespace monitoring --debug