name: Helm CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  helm_ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      - name: Instalar o Helm
        uses: azure/setup-helm@v4
        with:
          version: 'v3.15.2'

      - name: Adicionar Repositório do Grafana
        run: helm repo add grafana https://grafana.github.io/helm-charts

      - name: Atualizar Repositórios do Helm
        run: helm repo update
      
      - name: Validar Deploy do Chart do Grafana
        run: helm upgrade --install grafana grafana/grafana --namespace monitoring -f ./helm-charts/grafana/values.yaml --dry-run --debug