name: Helm CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  helm_ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      - name: Instalar o Helm
        uses: azure/setup-helm@v4
        with:
          version: 'v3.15.2'

      - name: Adicionar Repositório do Grafana
        run: helm repo add grafana https://grafana.github.io/helm-charts

      - name: Atualizar Repositórios do Helm
        run: helm repo update
      
      # vai funcionar porque o Chart.yaml existe
      - name: Lint (Validar a Sintaxe) do Chart
        run: helm lint helm-charts/grafana

      # renderiza o YAML final, sem precisar de um cluster
      - name: Template (Validar a Logica) do Chart
        run: helm template grafana grafana/grafana -f helm-charts/grafana/values.yaml --namespace monitoring --debug